# This workflow checks for issues relating to this repository's TypeScript challenges.

name: CI for TypeScript challenges

on:
  push:
    paths:
      - .github/workflows/typescript-challenges-ci.yml
      - typescript-challenges/**

jobs:
  ci:

    runs-on: windows-latest

    defaults:
       run:
         working-directory: ./typescript-challenges/

    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
        cache-dependency-path: typescript-challenges/package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npx eslint .
    - name: Check formatting
      if: success() || failure()
      run: npx prettier . --check
    - name: Test
      if: success() || failure()
      run: npm test
